[package]
name = "gameman"
version = "0.1.0"
authors = ["Bart Merenda <outsbart@gmail.com>"]

[dependencies]
log = "0.3.8"
env_logger = "0.4.3"
sdl2 = "0.30"
serde = "1.0"
serde_derive = "1.0.15"
csv = "1.0.0-beta.4"
lazy_static = "1.1.0"